### ISSUE TITLE
Bitfinex Losing market data connection

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#102]
Today around 16.45 I lost market data on nearly all of the Bitfinex markets.

See screenshot. Restarting Tribeca fixes the issue but I don't know what's it's due.
![capture d ecran 2017-05-24 a 16 57 21](https://cloud.githubusercontent.com/assets/6861590/26410024/6a98db0a-40a2-11e7-9ca2-8e51d5425d4b.png)

I think we can link to #90 

Ps: Sorry for flooding you with issues today!

**Comment by ctubio** [comment]
will keep the issue opened for a while in case im able to reproduce this (never happened to me on Bitfinex yet)

Ps: Hello Camille'¡ xD

**Comment by Camille92** [comment]
I think we're "lucky".

I opened it without forever and this is what I've got before it crashed.
Not 100% sure this is linked to losing market data but still interesting.

```
bitfinex TypeError: Cannot read property 'size' of undefined
    at Object.getQuoteAtTopOfMarket (/home/ubuntu/tribeca/app/server/quoting-styles/helpers.js:25:39)
    at computeBoomerangQuote (/home/ubuntu/tribeca/app/server/quoting-styles/ping-pong.js:68:30)
    at BoomerangQuoteStyle.GenerateQuote (/home/ubuntu/tribeca/app/server/quoting-styles/ping-pong.js:18:20)
    at QuotingEngine.computeQuote (/home/ubuntu/tribeca/app/server/quoting-engine.js:106:59)
    at Array.QuotingEngine.recalcQuote (/home/ubuntu/tribeca/app/server/quoting-engine.js:62:32)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:31:43)
    at MarketFiltration.set latestFilteredMarket [as latestFilteredMarket] (/home/ubuntu/tribeca/app/server/market-filtration.js:44:36)
    at Evt.MarketFiltration.filterFullMarket [as _singleCallback] (/home/ubuntu/tribeca/app/server/market-filtration.js:20:39)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:28:22)
    at Evt.MarketDataBroker.handleMarketData [as _singleCallback] (/home/ubuntu/tribeca/app/server/broker.js:24:29)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:28:22)
    at BitfinexMarketDataGateway.onDepth (/home/ubuntu/tribeca/app/server/gateways/bitfinex.js:183:29)
    at WebSocketClient.BitfinexWebsocket.onMessage [as internalOnMessage] (/home/ubuntu/tribeca/app/server/gateways/bitfinex.js:119:21)
    at native.client.group.onMessage (/home/ubuntu/tribeca/node_modules/uws/uws.js:57:15) Error parsing msg [113194,[16.079,2,-459.55304584]]
main Unhandled exception! TypeError: Cannot read property 'size' of undefined
    at Object.getQuoteAtTopOfMarket (/home/ubuntu/tribeca/app/server/quoting-styles/helpers.js:25:39)
    at computeBoomerangQuote (/home/ubuntu/tribeca/app/server/quoting-styles/ping-pong.js:68:30)
    at BoomerangQuoteStyle.GenerateQuote (/home/ubuntu/tribeca/app/server/quoting-styles/ping-pong.js:18:20)
    at QuotingEngine.computeQuote (/home/ubuntu/tribeca/app/server/quoting-engine.js:106:59)
    at Array.QuotingEngine.recalcQuote (/home/ubuntu/tribeca/app/server/quoting-engine.js:62:32)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:31:43)
    at MarketFiltration.set latestFilteredMarket [as latestFilteredMarket] (/home/ubuntu/tribeca/app/server/market-filtration.js:44:36)
    at Evt.MarketFiltration.filterFullMarket [as _singleCallback] (/home/ubuntu/tribeca/app/server/market-filtration.js:20:39)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:28:22)
    at Evt.MarketDataBroker.handleMarketData [as _singleCallback] (/home/ubuntu/tribeca/app/server/broker.js:24:29)
    at Evt.trigger (/home/ubuntu/tribeca/app/server/utils.js:28:22)
    at BitfinexMarketDataGateway.onDepth (/home/ubuntu/tribeca/app/server/gateways/bitfinex.js:183:29)
    at WebSocketClient.BitfinexWebsocket.onMessage [as internalOnMessage] (/home/ubuntu/tribeca/app/server/gateways/bitfinex.js:119:21)
    at native.client.group.onMessage (/home/ubuntu/tribeca/node_modules/uws/uws.js:57:15)
main All exiting event handlers have fired, exiting application.
main Exiting with code 0
```

**Comment by ctubio** [comment]
oh well, same as in https://github.com/ctubio/tribeca/issues/98

**Comment by Camille92** [comment]
Well then we know it's not only Coinbase!
