### ISSUE TITLE
New currency pairs on GDAX

### ISSUE THREAD

**Issue by ekienmeier** [ctubio/tribeca#119]
GDAX recently added ETH/EUR and LTC/EUR.
When I add ETH/EUR to the Dockerfile:
```
ENV EXCHANGE coinbase
ENV TradedPair ETH/EUR
```
I get the following error when starting Tribeca:
```
07:10:54.405 main Listening to admins on *: 3000
07:10:55.004 main Unhandled promise rejection! Error: unable to match pair to a coinbase symbol ETH/EUR
    at Object.<anonymous> (/tribeca/app/server/gateways/coinbase.js:373:15)
    at Generator.next (<anonymous>)
    at fulfilled (/tribeca/app/server/gateways/coinbase.js:4:58)
    at tryCatcher (/tribeca/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tribeca/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/tribeca/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/tribeca/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/tribeca/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/tribeca/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/tribeca/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/tribeca/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) Promise {
  _bitField: 18087936,
  _fulfillmentHandler0:
   Error: unable to match pair to a coinbase symbol ETH/EUR
       at Object.<anonymous> (/tribeca/app/server/gateways/coinbase.js:373:15)
       at Generator.next (<anonymous>)
       at fulfilled (/tribeca/app/server/gateways/coinbase.js:4:58)
       at tryCatcher (/tribeca/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/tribeca/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/tribeca/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/tribeca/node_modules/bluebird/js/release/promise.js:614:10)
       at Promise._settlePromises (/tribeca/node_modules/bluebird/js/release/promise.js:693:18)
       at Async._drainQueue (/tribeca/node_modules/bluebird/js/release/async.js:133:16)
       at Async._drainQueues (/tribeca/node_modules/bluebird/js/release/async.js:143:10)
       at Immediate.Async.drainQueues (/tribeca/node_modules/bluebird/js/release/async.js:17:14)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5),
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
```
Do these new currency pairs for this exchange be included somewhere in the code?

Thanks

**Comment by Camille92** [comment]
It works well for me with manual installation:)

**Comment by ctubio** [comment]
this error is saying that after requesting the products from https://api.gdax.com/products, ETH/EUR was not found, but https://api.gdax.com/products effectively have ETH/EUR, so this may be a temporary poblem?

what tribeca does is search of id ETH-EUR in https://api.gdax.com/products
can you simply try again?

**Comment by ekienmeier** [comment]
My apologies, I should do important things only with the proper amount of coffein...
It works just fine, as expected. The problem was the GDAX sandbox URLs in my Dockerfile. 😢
