### ISSUE TITLE
Missing Bindings

### ISSUE THREAD

**Issue by zachaller** [ctubio/tribeca#93]
I cant seem to get trebeca running anymore after this commit 2bee0af3f7173989df5eaaccfd66a25466389b80 the error is

```
> tribeca@2.0.0 test /root/tribeca
> mocha --compilers ts:ts-node/register test/*.ts


/root/tribeca/node_modules/bindings/bindings.js:88
  err = new Error('Could not locate the bindings file. Tried:\n'
        ^
Error: Could not locate the bindings file. Tried:
 → /root/tribeca/build/tribeca.node
 → /root/tribeca/build/Debug/tribeca.node
 → /root/tribeca/build/Release/tribeca.node
 → /root/tribeca/out/Debug/tribeca.node
 → /root/tribeca/Debug/tribeca.node
 → /root/tribeca/out/Release/tribeca.node
 → /root/tribeca/Release/tribeca.node
 → /root/tribeca/build/default/tribeca.node
 → /root/tribeca/compiled/7.10.0/linux/x64/tribeca.node
    at bindings (/root/tribeca/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/tribeca/src/server/statistics.ts:8:35)
    at Module._compile (module.js:571:32)
    at Module.m._compile (/root/tribeca/node_modules/ts-node/src/index.ts:385:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/root/tribeca/node_modules/ts-node/src/index.ts:388:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/tribeca/test/statistics_tests.ts:3:1)
    at Module._compile (module.js:571:32)
    at Module.m._compile (/root/tribeca/node_modules/ts-node/src/index.ts:385:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/root/tribeca/node_modules/ts-node/src/index.ts:388:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /root/tribeca/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/root/tribeca/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/root/tribeca/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/root/tribeca/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by ctubio** [comment]
i never used the app with root user, can you check if `npm install` has enough permissions to be able to create the file `/root/tribeca/build/Release/tribeca.node`?

if you run `rm -rf node_modules && npm install` inside `/root/tribeca`, does it creates `/root/tribeca/build/Release/tribeca.node`?

**Comment by ctubio** [comment]
not sure if it helps, but this was the log of the last run in travis: https://travis-ci.org/ctubio/tribeca/jobs/234996323#L136 (take it as an example please)

**Comment by zachaller** [comment]
hm.. I tried as a non root user it worked again just fine. I do not know why that changed all of a sudden it was working before but anyways its better to not run as root anyway.
